services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - file_mongo_db:/data/db

volumes:
  file_mongo_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: E:/Study/Project/image_mngt_file_service/mongo_data


#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: image-mngt-file-service
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mongodb
#    environment:
#      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/image_mngt_file_service

